name: Conditional sync to ParaTranz in parallel

on:
  workflow_call:
  workflow_dispatch:

jobs:
  zh_CN:
    uses: ./.github/workflows/conditional-sync-to-paratranz.yml
    with:
      target_lang: zh_CN
  ja_JP:
    uses: ./.github/workflows/conditional-sync-to-paratranz.yml
    with:
      target_lang: ja_JP
  ko_KR:
    uses: ./.github/workflows/conditional-sync-to-paratranz.yml
    with:
      target_lang: ko_KR
  pt_BR:
    uses: ./.github/workflows/conditional-sync-to-paratranz.yml
    with:
      target_lang: pt_BR
  fr_FR:
    uses: ./.github/workflows/conditional-sync-to-paratranz.yml
    with:
      target_lang: fr_FR
  es_ES:
    uses: ./.github/workflows/conditional-sync-to-paratranz.yml
    with:
      target_lang: es_ES
